In [ ]:
import pandas as pd
from data_generator_2 import RetailDataGenerator
from datetime import datetime
import boto3

:

In [3]:
data = pd.read_parquet('/mnt/d/Projects/Project-2-End-to-End-Retail-Analytics-Pipeline/retail_data_v2/transactions_2025-01-01.parquet')
data

,transaction_id,date,time,datetime,customer_id,store_id,store_name,cashier_id,payment_method,subtotal,...,promotion_code,refund_reason,status,product_id,product_name,category,quantity,unit_price,discount_percent,line_total
0,TXN20250101000001,NaT,None,NaT,CUST011266,ST005,Spence PLC Flagship,EMP049,Cash,301.13,...,None,None,Completed,PRD006350,Eco-Friendly Tent,Sports & Outdoors,1,143.582299,0.00,143.58
1,TXN20250101000001,NaT,None,NaT,CUST011266,ST005,Spence PLC Flagship,EMP049,Cash,301.13,...,None,None,Completed,PRD011769,Premium Thermometer,Health & Wellness,1,157.547476,0.00,157.55
2,TXN20250101000002,2025-01-01,19:19:48,2025-01-28 19:19:48,CUST053149,ST003,Morales-Jones Online,EMP037,Credit Card,1516.31,...,None,None,Completed,PRD000730,Modern Perfume,Beauty & Personal Care,2,71.157335,8.74,129.87
3,TXN20250101000002,2025-01-01,19:19:48,2025-01-28 19:19:48,CUST053149,ST003,Morales-Jones Online,EMP037,Credit Card,1516.31,...,None,None,Completed,PRD006600,Vintage Running Shoes,Sports & Outdoors,2,625.964450,0.00,1251.93
4,TXN20250101000002,2025-01-01,19:19:48,2025-01-28 19:19:48,CUST053149,ST003,Morales-Jones Online,EMP037,Credit Card,1516.31,...,None,None,Completed,PRD010357,Classic Calculator,Office Supplies,2,67.254830,0.00,134.51
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9459,DUPTXN20250101002394,2025-01-01,23:05:39,2025-01-01 23:05:39,CUST020849,ST027,Morales-Jones Online Branch,None,Digital Wallet,755.83,...,None,None,Failed,PRD004230,Eco-Friendly First Aid Kit,Health & Wellness,3,251.942673,0.00,755.83
9460,DUPTXN20250101000075,2025-01-01,12:51:19,2025-01-01 12:51:19,CUST010303,ST003,Morales-Jones Online,EMP058,Debit Card,4436.01,...,None,None,Completed,PRD004225,Eco-Friendly Monitor,Electronics,1,598.347501,0.00,598.35
9461,DUPTXN20250101000075,2025-01-01,12:51:19,2025-01-01 12:51:19,CUST010303,ST003,Morales-Jones Online,EMP058,Debit Card,4436.01,...,None,None,Completed,PRD001514,Modern Tent,Sports & Outdoors,3,87.182185,0.00,261.55
9462,DUPTXN20250101000075,2025-01-01,12:51:19,2025-01-01 12:51:19,CUST010303,ST003,Morales-Jones Online,EMP058,Debit Card,4436.01,...,None,None,Completed,PRD000752,Classic Speaker,Electronics,2,1788.057500,0.00,3576.12
9463,DUPTXN20250101003895,2025-01-01,19:18:00,2025-01-01 19:18:00,CUST005526,ST016,Herring and Sons Flagship,None,Credit Card,185.38,...,None,None,Completed,PRD008241,Vintage Leash,Pet Supplies,3,61.792638,0.00,185.38

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9464 entries, 0 to 9463
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   transaction_id         9464 non-null   object
 1   date                   9015 non-null   datetime64[ns]
 2   time                   9015 non-null   object
 3   datetime               9015 non-null   datetime64[ns]
 4   customer_id            9464 non-null   object
 5   store_id               9464 non-null   object
 6   store_name             9464 non-null   object
 7   cashier_id             7627 non-null   object
 8   payment_method         8505 non-null   object
 9   subtotal               9464 non-null   float64
 10  tax_amount             9464 non-null   float64
 11  total_amount           9464 non-null   float64
 12  items_count            9464 non-null   int64
 13  loyalty_points_earned  9464 non-null   int64
 14  promotion_code         952 non-null    object
 15  refund_reason          252 non-null    object
 16  status                 9464 non-null   object
 17  product_id             9464 non-null   object
 18  product_name           9464 non-null   object
 19  category               9464 non-null   object
 20  quantity               9464 non-null   int64
 21  unit_price             9464 non-null   float64
 22  discount_percent       9464 non-null   float64
 23  line_total             9464 non-null   float64
dtypes: datetime64[ns](2), float64(6), int64(3), object(13)
memory usage: 1.7+ MB

In [ ]:
import os

: